name: C/C++ CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: make exe
      run: chmod +x configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
    
