name: C/C++ CI

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v3
    - uses: Bhacaz/checkout-files@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        files: Makefile configure example.cpp hello.cpp helloTest.cpp
    - name: install cppunit
      run: sudo apt install -y libcppunit-dev
    - name: make exe
      run: chmod +x configure
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: make test
    
